#! /bin/sh
#
# Purpose:  Get a set of problem definition files from the PDE library.
#
# Author:   Michael Holst
# rcsid="$Id: difp,v 1.1.1.1 2007/04/27 08:28:04 hrg Exp $"

diff lib/pde/fu_v_$1.m    fu_v.m
diff lib/pde/dfu_wv_$1.m  dfu_wv.m
diff lib/pde/u_d_$1.m     u_d.m
diff lib/pde/u_t_$1.m     u_t.m
diff lib/pde/rho_$1.m     rho.m
diff lib/pde/mcin_$1.m    mcin.m

